name: adhere

on:
  pull_request:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx --yes @drkmttr/adhere validate
        env:
          TYPESAFE_API_KEY: ${{ secrets.TYPESAFE_API_KEY }}
